destination: public
sass:
    style: compressed
    sass_dir: assets/css
    load_paths: [ _includes/**/* ]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "Festiwal Ukraina w centrum Lublina 2020"
      description: "Zapraszamy w naszą wspólną wędrówkę w świat ukraiński. Tworzymy festiwal razem!"
      ogImage: "fb_preview.png"
imagesPrefix: 'assets/images/'
title: "Festiwal Ukraina w centrum Lublina 2020"
exclude:
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
